src/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from home.views import (
    home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view
    
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('study/', include('study.urls', 'study')),
    path('', home_screen_view, name="home"),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/study/urls.py
from django.urls import path

from study.views import (
	create_study_view,
	detail_study_view,
	edit_study_view,
)

app_name = 'study'

urlpatterns = [
    path('create/', create_study_view, name="create"),
    path('<slug>/', detail_study_view, name="detail"),
    path('<slug>/edit/', edit_study_view, name="edit"),
 ]

src/home/models.py
from django.db import models

# Create your models here.

src/home/views.py
from django.shortcuts import render
from account.models import Account
from study.models import Study
#from Study.views import get_project_queryset
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.
PROJECTS_PER_PAGE = 1

# Create your views here.
def home_screen_view(request):
    #print(request.headers)
    context = {}
    # context['some_string'] = "this is some sting that I am going to pass"
    
    # accounts = Account.objects.all()
    # context['accounts'] = accounts

    studies = Study.objects.all()
    context['studies'] = studies
    return render(request, "home/home.html", context)

src/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
.container {
    padding: 2rem 0rem;
    max-width: 90%;
  }
  
  h4 {
    margin: 2rem 0rem 1rem;
  }
  
  .table-image {
    td, th {
      vertical-align: middle;
    }
  
</style>

<div class="container">
    <h3 class="text-center">Landing page when user login</h3>
    
    <div class="d-flex flex-row-reverse p-4" >
        <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Select actions for the selected dataset
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Predefned Action 1</a>
              <a class="dropdown-item" href="#">Predefined Action 2</a>
              <a class="dropdown-item" href="#">Predefined Action 3</a>
            </div>
          </div>
    </div>
    
    
        
    <div class="table table-responsive">
    <table class="table w-100 small table-bordered table-striped">
        <thead>
            <tr>
                <th class="active">
                    <div class="checkbox select-all">
                          <input type="checkbox" class="check" id="all"> 
                      </div>
                </th>
                <th scope="col">Run</th>
                <th scope="col">Experiment</th>
                <th scope="col">Sample</th>
                <th scope="col">Study</th>
                <th scope="col">Taxid</th>
                <th scope="col">scientific_name</th>
                <th scope="col">Count</th>
                <th scope="col">Bases</th>
                <th scope="col">AvgLen</th>
                <th scope="col">Instrument</th>
                <th scope="col">LibraryLayout</th>
                <th scope="col">LibrarySelection</th>
                <th scope="col">LibrarySource</th>
                <th scope="col">Date created</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
    {% for study in studies %}
   
    {% for sample in study.samples.all %}
   
    {% for experiment in sample.experiments.all %}
    
    {% for run in experiment.runs.all %}
    
   
        
                <tr>
                    <td>
                        <div class="checkbox rows">
                        <input type="checkbox" class="check" value="{{experiment.title}}" id="{{experiment.id}}">
                    </div>
                </td>
        <!-- td><a href="{% url 'study:detail' study.slug %}">{{study.title}}</a> </td -->
         <td>{{run.name}}</td>
       
    
    <td>{{experiment.title}}</td>
    <td>{{sample.title}}</td>
    <td>{{study.title}}</td>
    <td>{{sample.taxon_id}}</td>
    <td>{{sample.scientific_name}}</td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
    <td>{{experiment.platform}}</td>
    <td>{{experiment.library_layout}}</td>
    <td>{{experiment.library_selection}}</td>
    <td>{{experiment.library_source}}</td>
    <td>{{study.date_created|date:'Y-m-d H:i'}}</td> 
    <td>processing</td>
    <td style='white-space: nowrap'>
        <button type="button" class="btn btn-primary btn-sm"><i class="far fa-eye"></i></button>
        <!-- button type="button" class="btn btn-success btn-sm"><i class="fas fa-edit"></i></button -->
      <button type="button" class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
      </td>
</tr>
    {% endfor %}
    {% endfor %}
    {% endfor %}
    {% endfor %}
</tbody>
</table>

</div>
</div>
{% endblock content %}